name: Build
 
on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
 
jobs:
  build:
    name: Build Bootstrapper
    runs-on: windows-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
     
    - name: Restore NuGet Packages
      run: nuget restore Bonsai.sln
 
    - name: Build Bonsai
      run: msbuild Bonsai.sln /t:Bonsai /p:Configuration=Release

    - name: Build Bonsai32
      run: msbuild Bonsai.sln /t:Bonsai32 /p:Configuration=Release

    - name: Build Tests
      run: msbuild Bonsai.sln /t:Bonsai_Core_Tests /t:Bonsai_System_Tests /t:Bonsai_Editor_Tests /p:Configuration=Release

    - name: Run Tests
      run: msbuild Bonsai.Tests.proj

#  installer:
#    name: Build Installer
#    needs: build
#    if: github.event_name == 'workflow_dispatch'
#    runs-on: windows-latest
#
#    steps:
    - name: Build Templates
      run: msbuild Bonsai.Templates/Bonsai.Templates.sln /p:Configuration=Release

    - name: Setup WiX
      run: nuget restore Bonsai.Setup.sln

    - name: Build Installer
      run: msbuild Bonsai.Setup.sln /p:Configuration=Release